### ISSUE TITLE
Disappearing kwargs

### ISSUE THREAD

**Issue by ryankzhu** [Degiacomi-Lab/molearn#5]
Hi! I get error when I do:

```
trainer.set_autoencoder(Small_AutoEncoder, out_points=data.dataset.shape[-1])
``` 

It seems that the kwargs given to set_autoencoder is not passed to initialise the foldingnet decoder:

```
Traceback (most recent call last):
  File "train.py", line 24, in <module>
    trainer.set_autoencoder(Small_AutoEncoder, out_points=data.dataset.shape[-1])
  File "/home/rzhu/Desktop/projects/molearn/src/molearn/trainers/trainer.py", line 76, in set_autoencoder
    self.autoencoder = autoencoder(**kwargs).to(self.device)
  File "/home/rzhu/Desktop/projects/molearn/src/molearn/models/small_foldingnet.py", line 45, in __init__
    super().__init__()
  File "/home/rzhu/Desktop/projects/molearn/src/molearn/models/foldingnet.py", line 244, in __init__
    self.decoder = Decoder(*args, **kwargs)
TypeError: __init__() missing 1 required positional argument: 'out_points'
```

**Comment by degiacom** [comment]
This seems to be caused by the fact that `Small_AutoEncoder` inherits from `AutoEncoder`, and that `super().__init__()` is called in its `__init__` method. I can see two solutions:

- pass `*args` and `*kwargs` to the `__init__` method of the superclass
- use multiple inheritance, and call instead the `__init__` method  of `nn.Module`.

Perhaps the former approach is better. @SCMusson?

**Comment by SCMusson** [comment]
Passing `*args` or `**kwargs` to `__init__` method would work but create the encoders and decoders twice. Using Multiple inheritance would do the same and avoid unnecessary work. `super(AutoEncoder, self).__init__()` should work I believe. Alternatively `super(type(self).__bases__[0], self).__init__()`. 
I pushed cf15651 which uses the former.
